### ISSUE TITLE
printError: Why?

### ISSUE THREAD

**Issue by fatboychummy** [1Turtle/gFont-cc#2]
Why does this repo use `printError` instead of `error`? It is not a good thing to do. If errors occur, there is no way of halting the program -- it will continue on even if something is critically wrong. There is no way to detect `printError` occurring via `pcall`/`xpcall` (as most error handlers use).

On top of that, it prints a message to output when you may not wish to have the error outputted immediately (say saving the error to a file or etc).

**Comment by SammyForReal** [comment]
Oh I didn't know that. I thought ``printError`` is just another way to print this. I will change this.

**Comment by SammyForReal** [comment]
Fixed issue in tag 1.0.2
